server:
  port: 8080
#数据库连接配置
spring:
  datasource:
    druid: 
      ##连接池jar
      db-type: com.alibaba.druid.pool.DruidDataSource
      ##连接数据库的jar
      driver-class-name: com.mysql.jdbc.Driver
      ##连接数据库路径
      url: jdbc:mysql://192.168.242.1:3306/hyll_springboot?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      ##账号
      username: root
      ##密码
      password: 123
      #初始化连接数
      initial-size: 5
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 20
      #从池中取连接的最大等待时间，单位ms
      max-wait: 60000
      #每60秒运行一次空闲连接回收器  
      time-between-eviction-runs-millis: 60000
      #池中的连接空闲30分钟后被回收 
      min-evictable-idle-time-millis: 300000
      #验证连接是否可用，使用的SQL语句
      validation-query: SELECT 1 FROM DUAL
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.  
      test-while-idle: true
      #借出连接时不要测试，否则很影响性能  
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 20
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有： 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      